# Generated by Django 4.2.16 on 2024-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
