# Generated by Django 4.2.16 on 2024-11-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartorderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='coupon',
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='core.coupon'),
        ),
    ]
