# Generated by Django 4.2.16 on 2024-11-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cartorderitem_coupon_cartorderitem_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=25),
        ),
    ]
